<?php 

$GLOBALS['SITE'] = "SOPER";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "SOPER";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "SOPER DEMO";
$GLOBALS[$SITE]['SYS'] = $GLOBALS[$SITE]['SYS_SLUG'];
$GLOBALS[$SITE]['URI'] = "DEMO/SOPER";

// 

?>